// [xihanzu-NR]
// GENERATED by serpent — edit the .hx file, not this one
import { ValueError, enumerate, int } from 'serpent-js';

function countdown(n) {
  while ((n > 0)) {
    if (((n % 2) === 0)) {
      console.log(`${n} (even)`);
    }
    n -= 1;
  }
  console.log("liftoff");
}
function first_match(xs, target) {
  for (const [i, x] of enumerate(xs)) {
    if ((x !== target)) {
      continue;
    }
    return i;
  }
  return (-1);
}
function parse_int(text) {
  try {
    return int(text);
  }
  catch (__err) {
    if (__err instanceof ValueError) {
      console.log(`not a number: ${text}`);
      return null;
    }
    else { throw __err; }
  }
  finally {
    console.log(`parse_int(${text}) done`);
  }
}
countdown(5);
console.log(`index of 3: ${first_match([1, 2, 3, 4], 3)}`);
console.log(`index of 9: ${first_match([1, 2, 3, 4], 9)}`);
console.log(`parse '42': ${parse_int('42')}`);
console.log(`parse 'xx': ${parse_int('xx')}`);
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiL3Jvb3Qvc2VycGVudC9kZW1vLWh4L2NvbnRyb2wuanMiLCJzb3VyY2VzIjpbIi9yb290L3NlcnBlbnQvZGVtby1oeC9jb250cm9sLmh4Il0sInNvdXJjZXNDb250ZW50IjpbIiMgW3hpaGFuenUtTlJdXG4jIENvbnRyb2wgZmxvdyB0aGF0IGhhcyBubyBwbGFjZSBpbiBhIGNvbXBvbmVudCB0cmVlLlxuXG5kZWYgY291bnRkb3duKG46IGludCk6XG4gICAgd2hpbGUgbiA+IDA6XG4gICAgICAgIGlmIG4gJSAyID09IDA6XG4gICAgICAgICAgICBwcmludChmXCJ7bn0gKGV2ZW4pXCIpXG4gICAgICAgIG4gLT0gMVxuICAgIHByaW50KFwibGlmdG9mZlwiKVxuXG5kZWYgZmlyc3RfbWF0Y2goeHM6IGxpc3QsIHRhcmdldDogaW50KTpcbiAgICBmb3IgaSwgeCBpbiBlbnVtZXJhdGUoeHMpOlxuICAgICAgICBpZiB4ICE9IHRhcmdldDpcbiAgICAgICAgICAgIGNvbnRpbnVlXG4gICAgICAgIHJldHVybiBpXG4gICAgcmV0dXJuIC0xXG5cbmRlZiBwYXJzZV9pbnQodGV4dDogc3RyKTpcbiAgICB0cnk6XG4gICAgICAgIHJldHVybiBpbnQodGV4dClcbiAgICBleGNlcHQgVmFsdWVFcnJvcjpcbiAgICAgICAgcHJpbnQoZlwibm90IGEgbnVtYmVyOiB7dGV4dH1cIilcbiAgICAgICAgcmV0dXJuIE5vbmVcbiAgICBmaW5hbGx5OlxuICAgICAgICBwcmludChmXCJwYXJzZV9pbnQoe3RleHR9KSBkb25lXCIpXG5cbmNvdW50ZG93big1KVxucHJpbnQoZlwiaW5kZXggb2YgMzoge2ZpcnN0X21hdGNoKFsxLCAyLCAzLCA0XSwgMyl9XCIpXG5wcmludChmXCJpbmRleCBvZiA5OiB7Zmlyc3RfbWF0Y2goWzEsIDIsIDMsIDRdLCA5KX1cIilcbnByaW50KGZcInBhcnNlICc0Mic6IHtwYXJzZV9pbnQoJzQyJyl9XCIpXG5wcmludChmXCJwYXJzZSAneHgnOiB7cGFyc2VfaW50KCd4eCcpfVwiKVxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUE7QUFBO0FBQTtBQUE7QUdBO0FDQTtBQ0E7QUNBO0FBQTtBQ0E7QUFBO0FDQTtBQUE7QUVBO0FDQTtBQ0E7QUNBO0FBQTtBQ0E7QUFBO0FDQTtBQUE7QUVBO0FDQTtBQ0E7QUFBO0FBQTtBQUE7QUVBO0FDQTtBQUE7QUFBO0FBQTtBQUE7QUVBO0FBQTtBQUE7QUVBO0FDQTtBQ0E7QUNBO0FDQSJ9
