// [xihanzu-NR]
// GENERATED by serpent — edit the .hx file, not this one
import { ValueError, enumerate, int } from 'serpent-js';

function countdown(n) {
  while ((n > 0)) {
    if (((n % 2) === 0)) {
      console.log(`${n} (even)`);
    }
    n -= 1;
  }
  console.log("liftoff");
}
function first_match(xs, target) {
  for (const [i, x] of enumerate(xs)) {
    if ((x !== target)) {
      continue;
    }
    return i;
  }
  return (-1);
}
function parse_int(text) {
  try {
    return int(text);
  }
  catch (__err) {
    if (__err instanceof ValueError) {
      console.log(`not a number: ${text}`);
      return null;
    }
    else { throw __err; }
  }
  finally {
    console.log(`parse_int(${text}) done`);
  }
}
countdown(5);
console.log(`index of 3: ${first_match([1, 2, 3, 4], 3)}`);
console.log(`index of 9: ${first_match([1, 2, 3, 4], 9)}`);
console.log(`parse '42': ${parse_int('42')}`);
console.log(`parse 'xx': ${parse_int('xx')}`);
//# sourceMappingURL=control.mjs.map
