// [xihanzu-NR]
// GENERATED by serpent — edit the .hx file, not this one
import { range } from 'serpent-js';

function fib(n) {
  if ((n < 2)) {
    return n;
  }
  return (fib((n - 1)) + fib((n - 2)));
}
function fib_list(count) {
  return range(count).map((i) => fib(i));
}
console.log(`first 10 fibonacci: ${fib_list(10)}`);
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiL3Jvb3Qvc2VycGVudC9kZW1vLWh4L2ZpYi5ocyIsInNvdXJjZXMiOlsiL3Jvb3Qvc2VycGVudC9kZW1vLWh4L2ZpYi5ocyJdLCJzb3VyY2VzQ29udGVudCI6WyIjIFt4aWhhbnp1LU5SXVxuIyBDbGFzc2ljIHJlY3Vyc2lvbiDigJQgdGhlIHRoaW5nIGBkZWZgIHNob3VsZCBtYWtlIHBhaW5sZXNzLlxuXG5kZWYgZmliKG46IGludCkgLT4gaW50OlxuICAgIGlmIG4gPCAyOlxuICAgICAgICByZXR1cm4gblxuICAgIHJldHVybiBmaWIobiAtIDEpICsgZmliKG4gLSAyKVxuXG5kZWYgZmliX2xpc3QoY291bnQ6IGludCkgLT4gbGlzdDpcbiAgICByZXR1cm4gW2ZpYihpKSBmb3IgaSBpbiByYW5nZShjb3VudCldXG5cbnByaW50KGZcImZpcnN0IDEwIGZpYm9uYWNjaToge2ZpYl9saXN0KDEwKX1cIilcbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBO0FBQTtBQUE7QUFBO0FHQTtBQ0E7QUNBO0FBQTtBQ0E7QUFBO0FFQTtBQ0E7QUFBO0FFQSJ9
