// [xihanzu-NR]
// GENERATED by serpent — edit the .hx file, not this one
import { range } from 'serpent-js';

function fib(n) {
  if ((n < 2)) {
    return n;
  }
  return (fib((n - 1)) + fib((n - 2)));
}
function fib_list(count) {
  return range(count).map((i) => fib(i));
}
console.log(`first 10 fibonacci: ${fib_list(10)}`);
//# sourceMappingURL=fib.mjs.map
