// [xihanzu-NR]
// GENERATED by serpent — edit the .hx file, not this one
import { sorted_by, sum, len, truthy } from 'serpent-js';

const SCORES = [({"name": "ada", "score": 92}), ({"name": "bob", "score": 78}), ({"name": "cyd", "score": 95})];
function average(rows) {
  if ((!truthy(rows))) {
    return 0.0;
  }
  return (rows.map((r) => r["score"]).reduce((a, b) => a + b, 0) / rows.length);
}
function top(rows, count) {
  const ranked = sorted_by(rows, ((r) => r["score"]));
  return ranked.slice().reverse().slice(0, count);
}
function passing(rows, threshold = 80) {
  return rows.filter((r) => (r["score"] >= threshold)).map((r) => r["name"]);
}
console.log(`average: ${average(SCORES)}`);
console.log(`top 2:   ${top(SCORES, 2)}`);
console.log(`passing: ${passing(SCORES)}`);
console.log(`passing at 90: ${passing(SCORES, 90)}`);
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiL3Jvb3Qvc2VycGVudC9kZW1vLWh4L3N0YXRzLmpzIiwic291cmNlcyI6WyIvcm9vdC9zZXJwZW50L2RlbW8taHgvc3RhdHMuaHgiXSwic291cmNlc0NvbnRlbnQiOlsiIyBbeGloYW56dS1OUl1cbiMgTGlzdC9kaWN0L2NvbXByZWhlbnNpb24gaWRpb21zIGEgUHl0aG9uIGRldiByZWFjaGVzIGZvciB3aXRob3V0IHRoaW5raW5nLlxuXG5mcm9tIHNlcnBlbnRfanMgaW1wb3J0IHNvcnRlZF9ieSwgc3VtLCBsZW4sIHRydXRoeVxuXG5TQ09SRVMgPSBbXG4gICAge1wibmFtZVwiOiBcImFkYVwiLCBcInNjb3JlXCI6IDkyfSxcbiAgICB7XCJuYW1lXCI6IFwiYm9iXCIsIFwic2NvcmVcIjogNzh9LFxuICAgIHtcIm5hbWVcIjogXCJjeWRcIiwgXCJzY29yZVwiOiA5NX0sXG5dXG5cbmRlZiBhdmVyYWdlKHJvd3M6IGxpc3QpIC0+IGZsb2F0OlxuICAgIGlmIG5vdCB0cnV0aHkocm93cyk6XG4gICAgICAgIHJldHVybiAwLjBcbiAgICByZXR1cm4gc3VtKFtyW1wic2NvcmVcIl0gZm9yIHIgaW4gcm93c10pIC8gbGVuKHJvd3MpXG5cbmRlZiB0b3Aocm93czogbGlzdCwgY291bnQ6IGludCkgLT4gbGlzdDpcbiAgICByYW5rZWQgPSBzb3J0ZWRfYnkocm93cywgbGFtYmRhIHI6IHJbXCJzY29yZVwiXSlcbiAgICByZXR1cm4gcmV2ZXJzZWQocmFua2VkKVswOmNvdW50XVxuXG5kZWYgcGFzc2luZyhyb3dzOiBsaXN0LCB0aHJlc2hvbGQ6IGludCA9IDgwKSAtPiBsaXN0OlxuICAgIHJldHVybiBbcltcIm5hbWVcIl0gZm9yIHIgaW4gcm93cyBpZiByW1wic2NvcmVcIl0gPj0gdGhyZXNob2xkXVxuXG5wcmludChmXCJhdmVyYWdlOiB7YXZlcmFnZShTQ09SRVMpfVwiKVxucHJpbnQoZlwidG9wIDI6ICAge3RvcChTQ09SRVMsIDIpfVwiKVxucHJpbnQoZlwicGFzc2luZzoge3Bhc3NpbmcoU0NPUkVTKX1cIilcbnByaW50KGZcInBhc3NpbmcgYXQgOTA6IHtwYXNzaW5nKFNDT1JFUywgOTApfVwiKVxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUE7QUFBO0FBQTtBQUE7QUtBO0FNQTtBQ0E7QUNBO0FBQTtBQ0E7QUFBO0FFQTtBQ0E7QUNBO0FBQTtBRUE7QUNBO0FBQTtBRUE7QUNBO0FDQTtBQ0EifQ==
