// [xihanzu-NR]
// GENERATED by serpent — edit the .hx file, not this one
import { sorted_by, sum, len, truthy } from 'serpent-js';

const SCORES = [({"name": "ada", "score": 92}), ({"name": "bob", "score": 78}), ({"name": "cyd", "score": 95})];
function average(rows) {
  if ((!truthy(rows))) {
    return 0.0;
  }
  return (rows.map((r) => r["score"]).reduce((a, b) => a + b, 0) / rows.length);
}
function top(rows, count) {
  const ranked = sorted_by(rows, ((r) => r["score"]));
  return ranked.slice().reverse().slice(0, count);
}
function passing(rows, threshold = 80) {
  return rows.filter((r) => (r["score"] >= threshold)).map((r) => r["name"]);
}
console.log(`average: ${average(SCORES)}`);
console.log(`top 2:   ${top(SCORES, 2)}`);
console.log(`passing: ${passing(SCORES)}`);
console.log(`passing at 90: ${passing(SCORES, 90)}`);
//# sourceMappingURL=stats.mjs.map
