# [xihanzu-NR]
[package]
name = "hydra"
version = "0.1.0"
edition = "2021"
description = "HydraScript compiler: Pythonic syntax for React (.hyx) and Node (.hys)"
license = "MIT"

[lib]
name = "hydra"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "hydra"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.test]
opt-level = 1
